### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alair069** [aabbcc872/DParticle#1]
Do you have Discord?
I want to buy some plugins

**Comment by aabbcc872** [comment]
Sorry.In our country,we can’t use it,because it isn’t allowed.And if you want,you can list your requirements to me.

**Comment by alair069** [comment]
Can I send you an email or Twitter?

**Comment by aabbcc872** [comment]
Ok,email is better.2220328339@qq.com.

**Comment by alair069** [comment]
Are saying that the email was not recognized

**Comment by aabbcc872** [comment]
ah?Can you give me your email?I will try to send an test email to you.

**Comment by alair069** [comment]
Okay, alairvha@gmail.com
